### ISSUE TITLE
Colombia National ID Back is not working ColombiaIdBackRecognizer?

### ISSUE THREAD

**Issue by kiritnim** [BlinkID/blinkid-react-native#80] opened 2018-10-10 07:04 UTC
Hi,

I Want to scan the Colombia National ID Card, The card have both side of the data, I Scan the front using **ColombiaIdFrontRecognizer** it's working fine and getting data of front. But at back side Use ColombiaIdBackRecognizer, There is not scanning process and nothing get results. Please help me how to scan the back part of Colombia.

**BACK**

![screen shot 2018-10-10 at 12 30 20 pm](https://user-images.githubusercontent.com/17870723/46718245-43358680-cc88-11e8-8cc2-f3f9c55642b9.png)

**==================================================================**

**FRONT**

![screen shot 2018-10-10 at 12 30 15 pm](https://user-images.githubusercontent.com/17870723/46718232-3add4b80-cc88-11e8-95af-650ae807b64d.png)

**Comment by i1E** [comment] 2018-10-10 08:20
Duplicate of https://github.com/BlinkID/blinkid-android/issues/130

**Closed by i1E** 2018-10-10 08:20 UTC
