### ISSUE TITLE
[IOS] Properties not found 4.8.0 update

### ISSUE THREAD

**Issue by ajboxjr** [BlinkID/blinkid-react-native#113] opened 2019-04-28 21:50 UTC
#### Description
Just updated from 4.7.0 and am having Issues getting my project to build successfully.  
- issuingAuthority & personalIdentificationNumber not found :/
#### Screenshots
<img width="341" alt="Screen Shot 2019-04-28 at 11 41 44 AM" src="https://user-images.githubusercontent.com/8427930/56867555-12126e80-69ac-11e9-8f4f-fcbb397638a2.png">
<img width="1047" alt="Screen Shot 2019-04-28 at 4 49 21 PM" src="https://user-images.githubusercontent.com/8427930/56870488-a5ac6500-69d5-11e9-8c1f-fe0403f7c985.png">

#### Files
MBSlovokiaCombinedRecognizerWrapper.m

#### To Reproduce
1. Update pods
2. Install ./initBlinkID.sh
3. link rnGesturehandler
4. build

thanks in advance!

**Comment by dCubelic** [comment] 2020-05-13 07:38
Hi, @ajboxjr 
sorry for the late answer.

Are you still having this issue? If so, best thing would be to upgrade to newest version.

I will close this issues now, feel free to reopen if the issue is unresolved.

Regards,
Dominik

**Closed by dCubelic** 2020-05-13 07:38 UTC
