### ISSUE TITLE
Build failing for ios

### ISSUE THREAD

**Issue by KBepo** [BlinkID/blinkid-react-native#115] opened 2019-05-24 10:06 UTC
We've been your customers for past year and half and had no issues what so ever. Today had to reinstall node_modules and ran pod install command as well. Everything went well with installation and linking. Version of react native is 0.58.5 as recommended and blink id version for pods is 4.9.1. However when I tried starting it on device everything went fine until xcode had to process blink id subproject. I've got tons of errors. And tried everything to repair but didn't succeed to make it work or to even start my project on device. I'm attaching photos of issues I'm getting in xcode. Please let me know if I can provide more info.

![Screenshot 2019-05-24 at 11 56 19](https://user-images.githubusercontent.com/7113018/58320586-46971000-7e1c-11e9-9d24-d354bd797661.png)

![Screenshot 2019-05-24 at 11 56 32](https://user-images.githubusercontent.com/7113018/58320593-4860d380-7e1c-11e9-9c99-362d5a839846.png)

P.S. speaking Croatian.

**Comment by dCubelic** [comment] 2020-05-13 07:41
Hi, @KBepo 
sorry for the late answer.

Are you still experiencing this issue?
If yes, you can try upgrading to the newest version and let us know the results.

I will close this issues now, feel free to reopen if the issue is unresolved.

Regards,
Dominik

**Closed by dCubelic** 2020-05-13 07:41 UTC
