### ISSUE TITLE
[Android] installation issue. 

### ISSUE THREAD

**Issue by jacky-ew** [BlinkID/blinkid-react-native#142] opened 2020-03-29 09:24 UTC
```
   > Could not find com.microblink:blinkid:5.3.0.
     Required by:
         project :app
         project :app > project :blinkid-react-native
```

even app is running, get error `"scanWithCamera" of undefined`

**Comment by i1E** [comment] 2020-03-30 06:41
Duplicate of #61

**Closed by i1E** 2020-03-30 06:41 UTC
